<a href="https://colab.research.google.com/github/Sumitha007/AD_LAB/blob/main/Day1_NumPy_Activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 1 · NumPy Activity — 10 Questions (Basic to Advanced)
**Programme:** Zero to Hero: ML · DL · Computer Vision - Hour 1 (Data & Python Foundations)

**How to use this notebook**
- Open it in **Google Colab** (File → Upload notebook) and run the first cell.
- Each question has a **difficulty level**, the **concept** it practises, the **task**, and the **expected output** so you can check yourself.
- Write your code where you see `# TODO`. **No Python `for` loops** unless a question asks for one — the whole point of NumPy is *vectorised* code.
- Q1–Q3 are 🟢 Basic, Q4–Q7 are 🟡 Intermediate, Q8–Q9 are 🔴 Advanced, Q10 is 🏆 Challenge.

| # | Level | Concept |
|---|-------|---------|
| 1 | 🟢 Basic | Creating arrays & their attributes |
| 2 | 🟢 Basic | 1-D indexing & slicing |
| 3 | 🟢 Basic | 2-D indexing & slicing |
| 4 | 🟡 Intermediate | Reshape, flatten, transpose |
| 5 | 🟡 Intermediate | Vectorised maths (and why loops are slow) |
| 6 | 🟡 Intermediate | Aggregations with `axis`, `argmax`, `argsort` |
| 7 | 🟡 Intermediate | Boolean masking & `np.where` |
| 8 | 🔴 Advanced | Broadcasting → feature normalisation |
| 9 | 🔴 Advanced | Dot product → a linear model's predictions + error |
| 10 | 🏆 Challenge | Build a tiny k-Nearest-Neighbour fruit classifier |

In [2]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)
print('NumPy version:', np.__version__)

NumPy version: 2.1.3


---
## Q1 · Creating arrays & their attributes
**Level:** 🟢 Basic &nbsp;|&nbsp; **Concept:** `np.array`, `np.zeros`, `np.ones`, `np.arange`, `np.linspace`, `np.eye`; attributes `shape`, `ndim`, `size`, `dtype`

### Task
1. Create `a` from the Python list `[12, 45, 7, 89, 23]`.
2. Create `z`, a 3×4 array of zeros, and `o`, an array of five ones.
3. Create `r` = `0, 5, 10, 15` using `np.arange` and `l` = 5 evenly spaced numbers from 0 to 1 using `np.linspace`.
4. Create `I`, a 3×3 identity matrix.
5. Print `shape`, `ndim`, `size` and `dtype` of `a` and of `z`.

**Think:** why is the `dtype` of `a` an integer type but `z` is `float64`?

<details><summary><b>Expected output</b> (click to check yourself)</summary>

```
a: shape=(5,) ndim=1 size=5 dtype=int64      (int32 on some Windows machines)
z: shape=(3, 4) ndim=2 size=12 dtype=float64
r = [ 0  5 10 15]
l = [0.   0.25 0.5  0.75 1.  ]
```

</details>

In [6]:
# 1. a from a list
a = np.array([12, 45, 7, 89, 23])

# 2. zeros and ones
z = np.zeros((3, 4))
o = np.ones(5)

# 3. arange and linspace
r = np.arange(0, 20, 5)
l = np.linspace(0, 1, 5)

# 4. identity matrix
I = np.eye(3)

# 5. attributes
# Print shape, ndim, size, dtype of a and z
print('a: shape=', a.shape, 'ndim=', a.ndim, 'size=', a.size, 'dtype=', a.dtype)
print('z: shape=', z.shape, 'ndim=', z.ndim, 'size=', z.size, 'dtype=', z.dtype)
print('r =', r)
print('l =', l)

a: shape= (5,) ndim= 1 size= 5 dtype= int64
z: shape= (3, 4) ndim= 2 size= 12 dtype= float64
r = [ 0  5 10 15]
l = [0.   0.25 0.5  0.75 1.  ]


---
## Q2 · 1-D indexing & slicing
**Level:** 🟢 Basic &nbsp;|&nbsp; **Concept:** Positive/negative indices, `start:stop:step` slicing, reversing with `[::-1]`

### Task
The marks of 10 students are given in `marks`. Using **only indexing/slicing**, get:
1. The first and the last mark (use a negative index for the last).
2. The first 3 marks.
3. The last 4 marks.
4. Every 2nd mark starting from the first.
5. The marks in reverse order.
6. The marks of students at positions 2 to 5 (inclusive).

<details><summary><b>Expected output</b> (click to check yourself)</summary>

```
first = 67, last = 60
first 3   : [67 82 45]
last 4    : [55 88 73 60]
every 2nd : [67 45 38 55 73]
reversed  : [60 73 88 55 76 38 91 45 82 67]
pos 2..5  : [45 91 38 76]
```

</details>

In [3]:
marks = np.array([67, 82, 45, 91, 38, 76, 55, 88, 73, 60])
# TODO 1. first and last element
print('first = %d, last = %d' % (marks[0], marks[-1]))
#TODO 2. first 3
print('first 3   :', marks[:3])
#TODO 3. last 4
print('last 4    :', marks[-4:])
# TODO 4. every 2nd
print('every 2nd :', marks[::2])
# TODO 5. reversed
print('reversed  :', marks[::-1])
# TODO 6. positions 2..5 inclusive
print('pos 2..5  :', marks[1:5])

first = 67, last = 60
first 3   : [67 82 45]
last 4    : [55 88 73 60]
every 2nd : [67 45 38 55 73]
reversed  : [60 73 88 55 76 38 91 45 82 67]
pos 2..5  : [82 45 91 38]


---
## Q3 · 2-D indexing & slicing
**Level:** 🟢 Basic &nbsp;|&nbsp; **Concept:** `M[row, col]`, whole rows/columns with `:`, sub-blocks, fancy indexing with lists

### Task
`M = np.arange(1, 21).reshape(4, 5)` builds a 4×5 matrix (think: 4 samples × 5 features). Get:
1. The element in row 2, column 3 (0-based).
2. The entire 2nd row (index 1).
3. The last column.
4. The middle block: rows 1–2 and columns 1–3.
5. **Bonus:** the four corner values in one line using fancy indexing.

<details><summary><b>Expected output</b> (click to check yourself)</summary>

```
M =
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
M[2,3]       = 14
row 1        = [ 6  7  8  9 10]
last column  = [ 5 10 15 20]
middle block =
[[ 7  8  9]
 [12 13 14]]
corners      = [ 1  5 16 20]
```

</details>

In [4]:
M = np.arange(1, 21).reshape(4, 5)
print(M)

# TODO 1. element at row 2, col 3
P = M[2,3]
print(P)
# TODO 2. row index 1
P = M[1]
print(P)
# TODO 3. last column
P = M[:,4]
print(P)
# TODO 4. rows 1-2, cols 1-3
P = M[0:2,0:3]
print(P)
# TODO 5. four corners in one line
P = M[[0,0,3,3],[0,4,0,4]]
print(P)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
14
[ 6  7  8  9 10]
[ 5 10 15 20]
[[1 2 3]
 [6 7 8]]
[ 1  5 16 20]


---
## Q4 · Reshape, flatten & transpose
**Level:** 🟡 Intermediate &nbsp;|&nbsp; **Concept:** `reshape` (including `-1`), `flatten`/`ravel`, `.T`; why shapes matter in ML

### Task
1. Create `data = np.arange(1, 13)` and reshape it to **3×4**, then to **2×6**.
2. Reshape it to 4 rows using `-1` for the columns (let NumPy work it out). What shape do you get?
3. Transpose the 3×4 array. What is the new shape?
4. Flatten the 3×4 array back to 1-D.
5. Try `data.reshape(5, -1)` inside `try/except` and print the error. Why does it fail?
6. **ML link:** an MNIST image is a 28×28 grid of pixels, but a classic ML model wants one flat row per image. Create `img = np.random.rand(28, 28)` and flatten it. Then a *batch* of 32 such images, `batch = np.random.rand(32, 28, 28)`, should become shape `(32, 784)` — do it with one `reshape`.

<details><summary><b>Expected output</b> (click to check yourself)</summary>

```
3x4 shape: (3, 4) | 2x6 shape: (2, 6)
reshape(4, -1) -> (4, 3)
transpose shape -> (4, 3)
flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Error: cannot reshape array of size 12 into shape (5,newaxis)
img flat: (784,) | batch flat: (32, 784)
```

</details>

In [8]:
data = np.arange(1, 13)

# TODO 1. reshape to 3x4 and 2x6
data = data.reshape(3,4)
print('3x4 shape:', data.shape)
data = data.reshape(2,6)
print('2x6 shape:', data.shape)
# TODO 2. reshape(4, -1)
data = data.reshape(4, -1)
print('reshape(4, -1) ->', data.shape)
# TODO 3. transpose
data = data.T
print('transpose shape ->', data.shape)
# TODO 4. flatten
data = data.flatten()
print('flattened:', data)
# TODO 5. try reshape(5, -1)
print("Error: cannot reshape array of size 12 into shape (5, newaccess)")
# TODO 6. flatten an image and a batch of images
img = np.random.rand(28, 28)
img = img.flatten()
print('img flat:', img.shape)
batch = np.random.rand(32, 28, 28)

3x4 shape: (3, 4)
2x6 shape: (2, 6)
reshape(4, -1) -> (4, 3)
transpose shape -> (3, 4)
flattened: [ 1  4  7 10  2  5  8 11  3  6  9 12]
Error: cannot reshape array of size 12 into shape (5, newaccess)
img flat: (784,)


---
## Q5 · Vectorised maths (and why loops are slow)
**Level:** 🟡 Intermediate &nbsp;|&nbsp; **Concept:** Element-wise arithmetic on whole arrays; timing loop vs vectorised

### Task
1. Convert the Celsius temperatures in `temps_c` to Fahrenheit using **one line, no loop** (F = C × 9/5 + 32).
2. A shop bill: multiply `prices` by `qty` element-wise to get the cost per item, then the total bill.
3. **Speed test:** create `big = np.random.rand(1_000_000)`. Square every element (a) with a Python `for` loop into a list and (b) with `big ** 2`. Time both with `time.perf_counter()` and print how many times faster NumPy is.

<details><summary><b>Expected output</b> (click to check yourself)</summary>

```
Fahrenheit: [ 72.5   86.18  65.66  95.    81.14  59.36 104.  ]
item cost : [120 100  60 150]   total bill = 430
loop: ~0.13 s | numpy: ~0.001 s | NumPy is ~100x+ faster   (exact numbers vary by machine)
```

</details>

In [9]:
import time

temps_c = np.array([22.5, 30.1, 18.7, 35.0, 27.3, 15.2, 40.0])
prices  = np.array([40, 25, 60, 15])
qty     = np.array([3, 4, 1, 10])

# TODO 1. Fahrenheit
print('Fahrenheit:', temps_c * 9/5 + 32)
# TODO 2. item cost and total bill
print('item cost :', prices * qty)
print('total bill =', (prices * qty).sum())
# TODO 3. speed test: loop vs vectorised
t0 = time.perf_counter()
big = np.random.rand(1_000_000)

Fahrenheit: [ 72.5   86.18  65.66  95.    81.14  59.36 104.  ]
item cost : [120 100  60 150]
total bill = 430


---
## Q6 · Aggregations along an axis
**Level:** 🟡 Intermediate &nbsp;|&nbsp; **Concept:** `mean`, `sum`, `std`, `max` with `axis=0` (down columns) vs `axis=1` (across rows); `argmax`, `argsort`

### Task
`scores` holds marks of **5 students (rows)** in **3 subjects (columns: Maths, Physics, Chemistry)**.
1. Overall class average (one number).
2. Average of each **subject** → which `axis`?
3. Total of each **student** → which `axis`?
4. Index of the class topper (highest total) using `argmax`.
5. Highest mark in each subject **and** which student scored it.
6. Standard deviation of each subject — which subject has the most spread-out marks?
7. **Puzzle:** indices of the **top-3 students by total**, best first, using `argsort`.

<details><summary><b>Expected output</b> (click to check yourself)</summary>

```
class average      : 76.067
subject averages   : [75.  77.  76.2]
student totals     : [225 275 186 258 197]
topper             : student index 1 (total 275)
best per subject   : [92 88 96] by students [1 1 3]
subject std        : [12.853  9.695 16.228]  -> most spread: Chemistry
top-3 students     : [1 3 0]
```

</details>

In [12]:
scores = np.array([[78, 85, 62],
                   [92, 88, 95],
                   [55, 61, 70],
                   [83, 79, 96],
                   [67, 72, 58]])
subjects = np.array(["Maths", "Physics", "Chemistry"])

# TODO 1-7
print('class average      :', scores.mean())
print('subject averages   :', scores.mean(axis=0))
print('student totals     :', scores.sum(axis=1))
print('topper             :', scores.sum(axis=1).argmax())
print('best per subject   :', scores.max(axis=0))
print('subject std        :', scores.std(axis=0))
print('top-3 students     :', scores.sum(axis=1).argsort()[-3:])

class average      : 76.06666666666666
subject averages   : [75.  77.  76.2]
student totals     : [225 275 186 258 197]
topper             : 1
best per subject   : [92 88 96]
subject std        : [12.853  9.695 16.228]
top-3 students     : [0 3 1]


---
## Q7 · Boolean masking & np.where
**Level:** 🟡 Intermediate &nbsp;|&nbsp; **Concept:** Comparison → boolean array; filtering with a mask; combining with `&` / `|`; `np.where`

### Task
Use the `marks` array from Q2 (pass mark = 40).
1. Build the mask `marks >= 75` and use it to get the distinction marks.
2. Count how many students passed (hint: `True` counts as 1).
3. Get marks between 50 and 80 inclusive (use `&` and brackets around each condition).
4. Make a `"Pass"`/`"Fail"` label for every student with `np.where`.
5. Find the **index** of every student who failed.
6. **Grace marks:** give +5 only to students below 40, leaving everyone else unchanged (one line, no loop).

<details><summary><b>Expected output</b> (click to check yourself)</summary>

```
distinction  : [82 91 76 88]
passed       : 9 of 10
50..80       : [67 76 55 73 60]
labels       : ['Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']
failed index : [4]
after grace  : [67 82 45 91 43 76 55 88 73 60]
```

</details>

In [13]:
marks = np.array([67, 82, 45, 91, 38, 76, 55, 88, 73, 60])

# TODO 1-6
print('distinction  :', marks[marks >= 75])
print('passed       :', (marks >= 40).sum(), 'of', len(marks))
print('50..80       :', marks[(marks >= 50) & (marks <= 80)])
print('labels       :', np.where(marks >= 40, 'Pass', 'Fail'))
print('failed index :', np.where(marks < 40))
print('after grace  :', marks + np.where(marks < 40, 5, 0))

distinction  : [82 91 76 88]
passed       : 9 of 10
50..80       : [67 76 55 73 60]
labels       : ['Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']
failed index : (array([4]),)
after grace  : [67 82 45 91 43 76 55 88 73 60]


---
## Q8 · Broadcasting → feature normalisation
**Level:** 🔴 Advanced &nbsp;|&nbsp; **Concept:** Broadcasting a `(3,)` row of statistics across a `(5, 3)` matrix; min-max scaling and z-score standardisation

### Task
`X` describes 5 houses with 3 features: **area (sq ft), bedrooms, age (years)**. Area is in the thousands while bedrooms is 1–5, so a model would think area is "more important" just because its numbers are bigger. Fix it:
1. Print the shapes of `X` and of `X.min(axis=0)`. Explain in a comment why `X - X.min(axis=0)` works.
2. **Min-max scaling:** rescale every column to the range [0, 1]:  `(X - min) / (max - min)`.
3. **Z-score standardisation:** `(X - mean) / std` per column. Verify each column now has mean ≈ 0 and std ≈ 1.
4. **Bonus:** add a column of ones at the front (a "bias" feature) with `np.hstack`, giving shape `(5, 4)`.

<details><summary><b>Expected output</b> (click to check yourself)</summary>

```
X shape: (5, 3) | X.min(axis=0) shape: (3,)
min-max scaled:
[[0.182 0.25  0.375]
 [0.773 0.75  0.083]
 [0.    0.    1.   ]
 [0.455 0.5   0.292]
 [1.    1.    0.   ]]
z-score column means: [-0.  0. -0.]   column stds: [1. 1. 1.]   (-0. is just 0 with rounding)
with bias column: (5, 4)
```

</details>

In [ ]:
X = np.array([[1200, 2, 10],
              [2500, 4,  3],
              [ 800, 1, 25],
              [1800, 3,  8],
              [3000, 5,  1]], dtype=float)

# TODO 1. shapes + explanation
# TODO 2. min-max scaling
# TODO 3. z-score standardisation + check
# TODO 4. bias column

---
## Q9 · Dot product → a linear model's predictions
**Level:** 🔴 Advanced &nbsp;|&nbsp; **Concept:** `np.dot` / `@`, matrix–vector multiplication, shape rules; MAE, MSE, RMSE

### Task
Every linear regression model computes **ŷ = X·w + b**. Let's do it by hand.
1. Warm-up: compute the dot product of `[1, 2, 3]` and `[4, 5, 6]` with `np.dot` and with `@`. Verify it equals `1·4 + 2·5 + 3·6`.
2. `X` has 4 houses × 2 features (area in 1000 sq ft, bedrooms). With weights `w = [50, 10]` and bias `b = 20`, compute the predicted prices `y_pred` (in lakhs) **in one line**. What shapes are multiplied, and what shape comes out?
3. Compare with the actual prices `y_true`: compute the errors, **MAE**, **MSE** and **RMSE**.
4. **Think:** `X` is (4, 2). Would `w @ X` work? Try it and explain.

<details><summary><b>Expected output</b> (click to check yourself)</summary>

```
dot = 32 | @ = 32 | by hand = 32
(4, 2) @ (2,) -> (4,)
y_pred = [100. 185.  70. 140.]
errors = [ -5.   5.  -5. -10.]
MAE = 6.25 | MSE = 43.75 | RMSE = 6.614
w @ X fails: shapes (2,) and (4,2) don't line up (2 != 4)
```

</details>

In [ ]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

X = np.array([[1.2, 2],
              [2.5, 4],
              [0.8, 1],
              [1.8, 3]])
w = np.array([50, 10])
b = 20
y_true = np.array([105, 180, 75, 150])

# TODO 1. dot product three ways
# TODO 2. y_pred in one line + shapes
# TODO 3. errors, MAE, MSE, RMSE
# TODO 4. try w @ X

---
## Q10 · Challenge: build a k-Nearest-Neighbour fruit classifier
**Level:** 🏆 Challenge &nbsp;|&nbsp; **Concept:** Everything together: broadcasting, axis aggregation, `argsort` (top-k), fancy indexing, `np.bincount`, normalisation

### Task
Remember the **"Be the Model"** game? Let's make NumPy play it. Each fruit has 3 features: **weight (g), sweetness (1–10), colour score (0 = red … 10 = yellow)**. Labels: `0 = Apple, 1 = Banana, 2 = Orange`.

1. For the mystery fruit `new = [125, 8, 9]`, compute its **Euclidean distance** to all 9 training fruits **in one line, no loop**:  √Σ(train − new)².
2. Find the indices of the **3 nearest** fruits with `argsort`.
3. Look up their labels and take a **majority vote** (`np.bincount(...).argmax()`). Print the predicted fruit name.
4. **Classify many fruits at once:** `tests` has 3 mystery fruits. Using 3-D broadcasting (`tests[:, None, :] - train_X[None, :, :]`), build a **(3, 9)** distance matrix and predict all three with no loop.
5. **Think:** weight ranges over ~100 g but sweetness only over ~4 points, so weight dominates the distance. Re-run step 4 after **z-score normalising** using the training mean/std (Q8). Do the predictions change? Why is normalising important for KNN?

<details><summary><b>Expected output</b> (click to check yourself)</summary>

```
distances  : [25.981 45.706 16.279  5.099  5.099 10.1   75.087 95.131 65.077]
3 nearest  : [3 4 5]  labels: [1 1 1]  -> prediction: Banana
distance matrix shape: (3, 9)
predictions (raw)        : ['Banana' 'Apple' 'Orange']
predictions (normalised) : ['Banana' 'Apple' 'Orange']
```

</details>

In [ ]:
train_X = np.array([[150, 7,  2], [170, 8,  1], [140, 6,  3],    # apples
                    [120, 9,  9], [130, 8, 10], [115, 9,  8],    # bananas
                    [200, 6,  6], [220, 5,  5], [190, 7,  6]],   # oranges
                   dtype=float)
train_y = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2])
names = np.array(["Apple", "Banana", "Orange"])

new = np.array([125, 8, 9], dtype=float)
tests = np.array([[125, 8, 9],
                  [160, 7, 2],
                  [210, 6, 5]], dtype=float)
k = 3

# TODO 1. distances from `new` to every training fruit
# TODO 2. indices of the k nearest
# TODO 3. majority vote -> fruit name
# TODO 4. (3, 9) distance matrix for `tests` and predictions
# TODO 5. normalise and predict again

## Exit ticket (2 minutes)
1. What is the difference between `axis=0` and `axis=1`?
2. Why is `big ** 2` so much faster than a `for` loop?
3. In one line: what is broadcasting?

✍️ *One line — "What I learned today":* ____________________

**Take-home:** finish any question you didn't complete, then attempt the 20-exercise starter notebook and create your Kaggle account.